new:
	cp configs/bookie_1.cfg configs/bookie_2.cfg
	sed -i 's/storage1/storage2/g' configs/bookie_2.cfg
	sed -i 's/19001/19002/g' configs/bookie_2.cfg

	cp configs/bookie_1.cfg configs/bookie_3.cfg
	sed -i 's/storage1/storage3/g' configs/bookie_3.cfg
	sed -i 's/19001/19003/g' configs/bookie_3.cfg